Bump SymbolicUtils.jl to 0.19
I'm having some trouble isolating the issue due to FromFile.jl eval. But it seems like it's:

```julia
using Metatheory
rhs = :(~(x^-1))
Metatheory.Syntax.makeconsequent(rhs)
[9:50 PM] julia> Metatheory.Syntax.makeconsequent(rhs)
ERROR: Error when parsing right hand side
Stacktrace:
 [1] error(s::String)
   @ Base .\error.jl:33
 [2] makeconsequent(expr::Expr)
   @ Metatheory.Syntax C:\Users\accou\.julia\dev\Metatheory\src\Syntax.jl:64
 [3] top-level scope
   @ REPL[2]:1
```

@shashi